name: Copy rule folder from public repository A to public repository B

on:
  workflow_dispatch:

jobs:
  copy_rule_folder:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository A
        uses: actions/checkout@v3
        with:
          repository: deezertidal/deezertidal.github.io
          ref: master
          path: repository-A

      - name: Checkout repository B
        uses: actions/checkout@v3
        with:
          repository: deezertidal/shadowrocket-rules
          ref: main
          path: repository-B

      - name: Copy rule folder from repository A to repository B
        run: cp -r ./deezertidal.github.io/rule ./shadowrocket-rules/

      - name: Commit and push changes to repository B
        uses: stefanzweifel/git-auto-commit-action@v4.9.2
        with:
          commit_message: "Copy rule folder from public repository A to public repository B"
          commit_options: "--author='<username> <<email>>'"
          branch: main
          directory: ./hadowrocket-rules/
          token: ${{ secrets.GITHUB_TOKEN }}
